[phases.setup]
nixPkgs = ['python314', 'postgresql']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'gunicorn event_management.wsgi:application --bind 0.0.0.0:$PORT'
