[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn event_management.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.14.2"
